import {
  ClearpipeArtifactDirection,
  ClearpipeExecutionNodeSnapshot,
  ClearpipeExecutionSnapshot,
} from '../../clearpipe-api.service';
import {ClearpipeStatusPresentation} from '../framework/clearpipe-ui.types';

export type ClearpipeExecutionNodeState =
  | 'submitted'
  | 'queued'
  | 'running'
  | 'completed'
  | 'failed'
  | 'aborted'
  | 'skipped'
  | 'cached';

export type ClearpipeExecutionPreflightReasonCode =
  | 'not_checked'
  | 'no_graph'
  | 'empty_graph'
  | 'unsaved_definition'
  | 'dirty_definition'
  | 'read_only'
  | 'lifecycle_busy'
  | 'stale_definition'
  | 'permission_denied'
  | 'execution_unavailable'
  | 'validation_failed'
  | 'queue_unavailable'
  | 'resource_unavailable'
  | 'generated_output_unavailable'
  | 'runtime_mapping_unavailable'
  | 'route_not_ready'
  | 'route_identity_mismatch'
  | 'request_failed';

export interface ClearpipeExecutionPreflightReason {
  readonly code: ClearpipeExecutionPreflightReasonCode;
  readonly message: string;
}

export interface ClearpipeRuntimeStep {
  readonly graphNodeId: string;
  readonly pipelineStepName: string;
}

/**
 * Generated by the server compiler. Browser code treats the stable runtime
 * step map as opaque evidence and never derives execution identities from
 * generated source lines or display labels.
 */
export interface ClearpipeRuntimeEvidence {
  readonly graphDigest: string;
  readonly steps: readonly ClearpipeRuntimeStep[];
}

export interface ClearpipeExecutionPreflight {
  readonly scopeKey: string | null;
  readonly state: 'idle' | 'checking' | 'ready' | 'blocked';
  readonly reasons: readonly ClearpipeExecutionPreflightReason[];
  readonly evidence: ClearpipeRuntimeEvidence | null;
}

export interface ClearpipeExecutionAction {
  readonly disabled: boolean;
  readonly disabledReason: string | null;
}

export interface ClearpipeExecutionRunState {
  readonly state: 'idle' | 'submitting' | 'reconciling' | 'submitted' | 'submitted_unwatched' | 'failed';
  readonly runTaskId: string | null;
  readonly message: string | null;
  readonly reason?: ClearpipeExecutionPreflightReasonCode;
  /** Retained until the adapter confirms or reconciles this submission. */
  readonly idempotencyKey?: string;
}

export interface ClearpipeExecutionController {
  readonly taskId: string;
  readonly status: string;
  readonly startedAt?: string;
  readonly completedAt?: string;
  readonly updatedAt?: string;
}

export interface ClearpipeExecutionArtifact {
  readonly id: string;
  readonly name: string;
  readonly type?: string;
  readonly direction?: ClearpipeArtifactDirection;
}

export interface ClearpipeExecutionModel {
  readonly id: string;
  readonly name?: string;
}

export interface ClearpipeExecutionDataset {
  readonly taskId: string;
  readonly name: string;
}

/**
 * This is a projection of an authorized CP-14 runtime record. `availability`
 * is deliberately separate from `state`: an unavailable record is visible
 * feedback, not an invented node lifecycle state.
 */
export interface ClearpipeNodeExecution {
  readonly graphNodeId: string;
  readonly availability: 'available' | 'unavailable';
  readonly state?: ClearpipeExecutionNodeState;
  readonly backendStatus?: string;
  readonly taskId?: string;
  readonly logTaskId?: string;
  readonly startedAt?: string;
  readonly completedAt?: string;
  readonly updatedAt?: string;
  readonly result?: 'success' | 'failure';
  readonly failureDetail?: string;
  readonly artifacts: readonly ClearpipeExecutionArtifact[];
  readonly artifactsTruncated: boolean;
  readonly models: Readonly<{
    input: readonly ClearpipeExecutionModel[];
    output: readonly ClearpipeExecutionModel[];
  }>;
  readonly datasets: readonly ClearpipeExecutionDataset[];
}

export interface ClearpipeExecutionTracking {
  readonly state: 'idle' | 'polling' | 'completed' | 'partial' | 'stale' | 'denied' | 'unavailable' | 'failed';
  readonly message: string | null;
  readonly controller: ClearpipeExecutionController | null;
  readonly receivedNodes: number;
  readonly totalNodes: number | null;
}

export interface ClearpipeExecutionPresentation {
  readonly preflight: ClearpipeExecutionPreflight;
  readonly run: ClearpipeExecutionRunState;
  readonly tracking: ClearpipeExecutionTracking;
  readonly nodes: readonly ClearpipeNodeExecution[];
}

export interface ClearpipeExecutionSnapshotPage {
  readonly snapshot: ClearpipeExecutionSnapshot;
  readonly records: readonly ClearpipeExecutionNodeSnapshot[];
}

export type ClearpipeNodeStatusSelector = (nodeId: string) => readonly ClearpipeStatusPresentation[];
