{{- if and .Values.clearpipeScheduler.enabled (not .Values.clearpipeScheduler.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clearml.fullname" . }}-clearpipe-scheduler
  labels:
    {{- include "clearml.labels" . | nindent 4 }}
    clearml.component: clearpipe-scheduler
type: Opaque
stringData:
  access_key: {{ required "clearpipeScheduler.apiCredentials.accessKey is required when clearpipeScheduler.existingSecret is not set" .Values.clearpipeScheduler.apiCredentials.accessKey | quote }}
  secret_key: {{ required "clearpipeScheduler.apiCredentials.secretKey is required when clearpipeScheduler.existingSecret is not set" .Values.clearpipeScheduler.apiCredentials.secretKey | quote }}
{{- end }}
