{{- if and .Values.apiserver.enabled .Values.runaiWorker.enabled .Values.runaiWorker.caCert.enabled }}
{{- if and (not .Values.runaiWorker.caCert.existingSecret) .Values.runaiWorker.caCert.content }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "runaiWorker.referenceName" . }}-ca
  labels:
    {{- include "clearml.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.runaiWorker.caCert.secretKey }}: {{ .Values.runaiWorker.caCert.content | b64enc | quote }}
{{- end }}
{{- end }}
