_description: "Native ClearPipe pipeline definition management."

create {
    "2.35" {
        request { type: object }
        response { type: object }
    }
}
get_all {
    "2.35" {
        request { type: object }
        response { type: object }
    }
}
get_by_id {
    "2.35" {
        request { type: object }
        response { type: object }
    }
}
update {
    "2.35" {
        request { type: object }
        response { type: object }
    }
}
validate {
    "2.35" {
        request { type: object }
        response { type: object }
    }
}
start {
    "2.35" {
        request { type: object }
        response { type: object }
    }
}
archive {
    "2.35" {
        request { type: object }
        response { type: object }
    }
}
delete {
    "2.35" {
        request { type: object }
        response { type: object }
    }
}
parse_script {
    "2.35" {
        request { type: object }
        response { type: object }
    }
}

