apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clearml-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: clearml-charts
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: clearml-server
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/NaveDanan/clearml-kube.git
    path: clearml-charts
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
        - esa-values.yaml
