apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clearml-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: clearml-charts
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: clearml-server
  syncPolicy:
    automated:
      allowEmpty: false
      prune: false
      selfHeal: true
    retry:
      limit: 8
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
  source:
    repoURL: https://github.com/NaveDanan/clearml-kube.git
    path: clearml-charts
    targetRevision: master
    helm:
      releaseName: clearml-server
      valueFiles:
        - values.yaml
        - values-k3s-mmems.yaml
