apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clearml-auth-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: infra/clearml-auth-secrets
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: clearml-server
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/NaveDanan/clearml-kube.git
    path: infra/clearml-auth-secrets
    targetRevision: main
    directory:
      recurse: true
