apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: infra/keycloak
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: clearml-tools
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/NaveDanan/clearml-kube
    path: infra/keycloak
    targetRevision: HEAD
    directory:
      recurse: true
